### ISSUE TITLE
Linux support/Library update/Compilation Errors

### ISSUE THREAD

**Issue by IntegratedQuantum** [Aeneas137/starflight-tlc#24]
A few days ago I heard about this project and started playing the game(luckily I was able to run it with wine on linux).
I liked the game although it has some issues and decided to help make it better.
As I tried to compile it I noticed a few things:
1. The libraries are pretty old.
2. Most of the libraries are made for windows only → I'm not able to compile the game
3. While desperately trying to make it compile I had a few errors inside the game itself:
itoa(): [This function is not defined in ANSI-C and is not part of C++](http://www.cplusplus.com/reference/cstdlib/itoa/) → compiler error
There are many classes like `OrbitPlanet` that contain undefined classes like `IOrbitPlanetEvent`.
There are many classes like `OrbitPlanet` that reference the class Requirement without including "Requirement.h".
There are many classes like `OrbitPlanet` that us a nonexistend function like: Game::questMgr->OrbitPlanetEventMgr.Register(this);
The CombatPlayerVessel references the nonexistend functions Move and Draw of its super-type.

The last few errors make me wonder how you were able to even compile it in windows.

I would like to help, but I don't know how all those libraries were supposed to work, so I can't help changing the libraries.

**Comment by Anarchian** [comment]
This solution builds with VS2010. It's not a good idea to update old but reliable code to the newest tools or libs just because they're new. It's fine if you want to do so in a branch. The problems with the game lie with design and gameplay. I recommend making improvements to known good code rather than trying to force it to fit into your preferred environment. But that's just a suggestion. (Commercial games are never upgraded, due to introducing potential new bugs).

Did you see the link to the VS2010 Express installer? If it's still a valid url (and it was one year ago, the last time i checked), install that into WINE. 

If you're determined to compile it on Linux, that's your choice, but we've gone down that road before and it's a waste of time imo.

**Comment by Anarchian** [comment]
p.s. I'm just offering suggestions. Steve Wirsz is managing the repo. Due to the DirectX resolution code that I just remembered, this game probably won't build for Linux without rewriting a lot of code. That was a design decision, with no regrets. Linux is a waste of time.

**Comment by IntegratedQuantum** [comment]
I tried as you suggested to use VS using wine, but it didn't work.
Then I installed Windows 7 in VirtualBox and installed VS2010Express on it.
And surprisingly it was able to compile.
The executable produced is just not able to run properly. When I start it on the VM I get a window stating `Error initializing graphics`.
When I start the executable with wine instead, I get following errors:
```
005f:err:module:import_dll Library alld42.dll (which is needed by L"Z:\\home\\javafan\\starflight-tlc\\bin\\starflighttlcd.exe") not found
005f:err:module:import_dll Library MSVCR100D.dll (which is needed by L"Z:\\home\\javafan\\starflight-tlc\\bin\\lua5.1d.dll") not found
005f:err:module:import_dll Library lua5.1d.dll (which is needed by L"Z:\\home\\javafan\\starflight-tlc\\bin\\starflighttlcd.exe") not found
```

> Linux is a waste of time.

Just because you don't use it doesn't mean that nobody/almost nobody uses it.
Also linux is home to many developers(which might help this project) because it is a lot more developer-friendly than windows will ever get.

By the way all I described above cost roughly 5 hours of my time without yielding any useful results. So I would rather say Windows is a waste of time.

> It's not a good idea to update old but reliable code to the newest tools or libs just because they're new.

I know, but most newer libs are still developing and therefor can also fix those new bugs. This is a low price if your libs miss substantial features(like availability for other OS's).

> I recommend making improvements to known good code rather than trying to force it to fit into your preferred environment.

I would like to, but if I can't fit it in **any** environment that I can create on my computer, I need to do that.

> rewriting a lot of code

Maybe, but I think there are some easier workarounds(like using similar headers to connect to another library).

**Comment by Anarchian** [comment]
This will be my last reply because I'm not interested in talking with you about Linux. It is a waste of time with THIS code, not as an OS. I thought that was easy to interpret from the context of my words?  Do what you want, it's open source. Maybe some other Linux coders will take an interest in porting this old game. You'll have to rewrite all of the resolution code since DirectX is used to poll the video card.

**Comment by swirsz** [comment]
A full decade ago another contributor spent a lot of time and broke a lot of features to make the code GCC compatible.  He packaged up a tarball of what I believe is an Debian-compatible version of the game: http://www.starflt.com/starflighttlc-beta4-Linux.tar.gz

Unfortunately I don't have the source for this release and it is obviously very outdated.

The problem would be to either obtain a copy of the source code that this contributor had at this point and then try to shove 10 years worth of updates into this code, or as mentioned above, start with the current project and rewrite extensive parts of it.

If you want to pursue this approach, let me know.

**Comment by IntegratedQuantum** [comment]
No, updating that old code(if it still exists) wouldn't be an option(even remaking the whole project from scratch would be easier than finding and integrating 10 years of updates).

So I will try and work on the second approach.

**Comment by Anarchian** [comment]
It would be nice if you would create a branch so that general improvements will work with the original Windows version, while Linux specifics will stay in the branch. Some of the libs are embedded (like Perlin), so that shouldn't be a problem, but some are linked (like FMOD), and given its age, this is why I recommended just running the game in WINE. Did you install DirectX in your WINE setup? The VS2010 redistributables and DirectX runtime are needed. (The only thing DirectX is being used for is polling the video card for resolutions, not rendering).

**Comment by IntegratedQuantum** [comment]
No I didn't(and it seems rather complex on first sight).
But the project also didn't run on my virtual machine which has DirectX 11 installed.
Are "Direct3D Acceleration" or "APG Texture Acceleration" needed? It says "not available" on those.

**Comment by Anarchian** [comment]
Okay, maybe your DirectX install is fine then. Like I said, it's only used to poll the available resolutions from your video card, not to render.

Your WINE window is running at too low a res:
Desktop resolution: 1068 x 680
Desktop color depth: 24
Settings resolution: 1680,1050
You can edit the target resolution in the settings file but make it reasonable and standard.

Also don't worry about the PDB warnings, those are debug files, not needed.

**Comment by IntegratedQuantum** [comment]
Now it's working. Thanks for your help.
Although I now can build it for windows I will still work on a linux-build.
